site_name: VectorSearch (VS)
theme:
  name: material

nav:
  - Introduction: docs/index.md
  - Getting Started with Python: docs/python_start.md
  - Getting Started with C++: docs/cpp_start.md
  - Benchmarks: docs/benchmarks.md
  - FAQ: docs/faq.md
  - API: docs/api.md
